export default {
  height:'auto',
  calcHeight: 30,
  tip: false,
  searchShow: true,
  searchMenuSpan: 6,
  border: true,
  index: false,
  viewBtn: false,
  addBtn: false,
  editBtn:false,
  delBtn:false,
  selection: true,
  dialogClickModal: false,
  column: [
    {
      label: "主键",
      prop: "id",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "租户ID",
      prop: "tenantId",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      width:200,
      label: "名称",
      prop: "name",
      type: "input",
      search: true,
    },
    {
      width:80,
      label: "类型",
      prop: "type",
      type: "radio", 
    },
   
    {
      width:70,
      label: "券面额",
      prop: "amount",
      type: "input",
    },
    {
      width:70,
      label: "使用门槛",
      prop: "enough",
      type: "input",
    },
    {
      width:70,
      label: "库存",
      prop: "stock",
      type: "input",
    },
    {
      width:80,
      label: "每人限制",
      prop: "useLimit",
      type: "input",
      addDisplay: true,
      editDisplay: true,
      viewDisplay: true,
      hide: true, 
    },
    {
      label: "领取时间",
      prop: "gettime",
      type: "input" 
    },
    {
      label: "使用时间",
      prop: "usetime",
      type: "input" 
    },
    {
      label: "描述",
      prop: "description",
      type: "textarea",
      addDisplay: true,
      editDisplay: true,
      viewDisplay: true,
      hide: true, 
    },
     
    {
      label: "适用商品",
      prop: "goodsIds",
      type: "input",
      addDisplay: true,
      editDisplay: true,
      viewDisplay: true,
      hide: true, 
    },      
    {
      label: "状态",
      prop: "status",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: true,
      hide: true,
    } 
  ]
}
