export default {
  height:'auto',
  calcHeight: 30,
  tip: false,
  searchShow: true,
  searchMenuSpan: 6,
  border: true,
  index: true,
  viewBtn: true,
  selection: true,
  dialogClickModal: false,
  column: [
    {
      label: "主键",
      prop: "id",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "租户ID",
      prop: "tenantId",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "用户",
      prop: "userId",
      type: "input",
    },
    {
      label: "用户昵称",
      prop: "userNickname",
      type: "input",
      search: true,
    },
    {
      label: "头像",
      prop: "userAvatar",
      type: "input",
    },
    {
      label: "团",
      prop: "grouponId",
      type: "input",
    },
    {
      label: "商品",
      prop: "goodsId",
      type: "input",
    },
    {
      label: "商品规格",
      prop: "goodsSkuPriceId",
      type: "input",
    },
    {
      label: "活动",
      prop: "activityId",
      type: "input",
    },
    {
      label: "是否团长",
      prop: "isLeader",
      type: "input",
    },
    {
      label: "是否虚拟用户",
      prop: "isFictitious",
      type: "input",
    },
    {
      label: "订单",
      prop: "orderId",
      type: "input",
    },
    {
      label: "是否退款",
      prop: "isRefund",
      type: "input",
    },
    {
      label: "创建人",
      prop: "createUser",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "创建部门",
      prop: "createDept",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "创建时间",
      prop: "createTime",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
      search: true,
    },
    {
      label: "修改人",
      prop: "updateUser",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "修改时间",
      prop: "updateTime",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "是否已删除",
      prop: "isDeleted",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
  ]
}
