export default {
  height:'auto',
  calcHeight: 30,
  tip: false,
  searchShow: true,
  searchMenuSpan: 6,
  border: true,
  index: true,
  viewBtn: true,
  selection: true,
  dialogClickModal: false,
  column: [
    {
      label: "主键",
      prop: "id",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "租户ID",
      prop: "tenantId",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "活动名称",
      prop: "title",
      type: "input",
      span: 24,
      rules: [{
        required: true,
        message: "请输入活动名称",
        trigger: "blur"
      }],
    },
    {
      label: "商品组",
      prop: "goodsIds",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "类型",
      prop: "type",
      type: "input",
      span: 24,
      rules: [{
        required: true,
        message: "请输入类型",
        trigger: "blur"
      }],
    },
    {
      label: "活动说明",
      prop: "richtextId",
      type: "input",
    },
    {
      label: "说明标题",
      prop: "richtextTitle",
      type: "input",
    },
    {
      label: "开始时间",
      prop: "starttime",
      type: "date",
      format: "yyyy-MM-dd hh:mm:ss",
      valueFormat: "yyyy-MM-dd hh:mm:ss",
      rules: [{
        required: true,
        message: "请输入开始时间",
        trigger: "blur"
      }],
    },
    {
      label: "结束时间",
      prop: "endtime",
      type: "date",
      format: "yyyy-MM-dd hh:mm:ss",
      valueFormat: "yyyy-MM-dd hh:mm:ss",
      rules: [{
        required: true,
        message: "请输入结束时间",
        trigger: "blur"
      }],
    },
    {
      label: "活动规则",
      prop: "rules",
      type: "select",
      rules: [{
        required: true,
        message: "请输入活动规则",
        trigger: "blur"
      }],
    },
    {
      label: "创建人",
      prop: "createUser",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "创建部门",
      prop: "createDept",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "创建时间",
      prop: "createTime",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "修改人",
      prop: "updateUser",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "修改时间",
      prop: "updateTime",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "是否已删除",
      prop: "isDeleted",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
  ]
}
