export default {
  size: 'small',
  expand: false,
  index: true,
  border: true,
  selection: true,
  column: [
    {
      label: "主键",
      prop: "id",
      display: false,
      hide: true,
    },
    {
      label: "租户ID",
      prop: "tenantId",
      display: false,
      hide: true,
    },
    {
      label: "名称",
      prop: "name",
      span: 24,
      search: true,
    },
    {
      label: "类型:cash=代金券,discount=折扣券",
      prop: "type",
      search: true,
    },
    {
      label: "适用商品",
      prop: "goodsIds",
      display: false,
      hide: true,
    },
    {
      label: "券面额",
      prop: "amount",
      display: false,
      hide: true,
    },
    {
      label: "消费门槛",
      prop: "enough",
      display: false,
      hide: true,
    },
    {
      label: "库存",
      prop: "stock",
      display: false,
      hide: true,
    },
    {
      label: "每人限制",
      prop: "limit",
      display: false,
      hide: true,
    },
    {
      label: "领取周期",
      prop: "gettime",
      format: "yyyy-MM-dd hh:mm:ss",
      valueFormat: "yyyy-MM-dd hh:mm:ss",
      display: false,
      hide: true,
    },
    {
      label: "有效期",
      prop: "usetime",
      format: "yyyy-MM-dd hh:mm:ss",
      valueFormat: "yyyy-MM-dd hh:mm:ss",
      display: false,
      hide: true,
    },
    {
      label: "描述",
      prop: "description",
      display: false,
      hide: true,
    },
    {
      label: "",
      prop: "usetimestart",
      display: false,
      hide: true,
    },
    {
      label: "",
      prop: "usetimeend",
      display: false,
      hide: true,
    },
    {
      label: "",
      prop: "gettimestart",
      format: "yyyy-MM-dd hh:mm:ss",
      valueFormat: "yyyy-MM-dd hh:mm:ss",
      display: false,
      hide: true,
    },
    {
      label: "",
      prop: "gettimeend",
      format: "yyyy-MM-dd hh:mm:ss",
      valueFormat: "yyyy-MM-dd hh:mm:ss",
      display: false,
      hide: true,
    },
    {
      label: "创建人",
      prop: "createUser",
      display: false,
      hide: true,
    },
    {
      label: "创建部门",
      prop: "createDept",
      display: false,
      hide: true,
    },
    {
      label: "创建时间",
      prop: "createTime",
      display: false,
      hide: true,
    },
    {
      label: "修改人",
      prop: "updateUser",
      display: false,
      hide: true,
    },
    {
      label: "修改时间",
      prop: "updateTime",
      display: false,
      hide: true,
    },
    {
      label: "是否已删除",
      prop: "isDeleted",
      display: false,
      hide: true,
    },
  ]
}
