export default {
  height:'auto',
  calcHeight: 30,
  tip: false,
  searchShow: true,
  searchMenuSpan: 6,
  border: true,
  index: true,
  viewBtn: true,
  selection: true,
  dialogClickModal: false,
  column: [
    {
      label: "主键",
      prop: "id",
      type: "input",
    },
    {
      label: "租户ID",
      prop: "tenantId",
      type: "input",
    },
    {
      label: "订单号",
      prop: "orderId",
      type: "input",
      search: true,
    },
    {
      label: "订单商品",
      prop: "orderItemId",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "下单用户",
      prop: "buyerId",
      type: "input",
      search: true,
    },
    {
      label: "分销订单",
      prop: "commissionOrderId",
      type: "input",
    },
    {
      label: "分销用户",
      prop: "agentId",
      type: "input",
      search: true,
    },
    {
      label: "打款方式:money=余额,score=积分,cash=现金(手动打款),change=企业付款到零钱,bank=企业付款到银行卡",
      prop: "type",
      type: "input",
    },
    {
      label: "佣金",
      prop: "commission",
      type: "input",
    },
    {
      label: "原始佣金",
      prop: "originalCommission",
      type: "input",
    },
    {
      label: "执行层级",
      prop: "commissionLevel",
      type: "input",
    },
    {
      label: "执行等级",
      prop: "agentLevel",
      type: "input",
    },
    {
      label: "执行规则",
      prop: "commissionRules",
      type: "input",
    },
    {
      label: "创建人",
      prop: "createUser",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "创建部门",
      prop: "createDept",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "创建时间",
      prop: "createTime",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "修改人",
      prop: "updateUser",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "修改时间",
      prop: "updateTime",
      type: "input",
    },
    {
      label: "状态:-2=已取消,-1=已退回,0=待入账,1=已入账",
      prop: "status",
      type: "input",
      search: true,
    },
    {
      label: "是否已删除",
      prop: "isDeleted",
      type: "input",
    },
  ]
}
