export default {
  height:'auto',
  calcHeight: 30,
  tip: false,
  searchShow: true,
  searchMenuSpan: 6,
  border: true,
  index: true,
  viewBtn: true,
  selection: true,
  dialogClickModal: false,
  column: [
    {
      label: "主键",
      prop: "id",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "",
      prop: "goodsSkuIds",
      type: "input",
    },
    {
      label: "所属产品",
      prop: "goodsId",
      type: "input",
    },
    {
      label: "排序",
      prop: "weigh",
      type: "input",
    },
    {
      label: "缩略图",
      prop: "image",
      type: "input",
    },
    {
      label: "库存",
      prop: "stock",
      type: "input",
    },
    {
      label: "已售",
      prop: "sales",
      type: "input",
    },
    {
      label: "货号",
      prop: "sn",
      type: "input",
    },
    {
      label: "重量(kg)",
      prop: "weight",
      type: "input",
    },
    {
      label: "价格",
      prop: "price",
      type: "input",
    },
    {
      label: "中文规格",
      prop: "goodsSkuText",
      type: "input",
    },
    {
      label: "创建人",
      prop: "createUser",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "创建部门",
      prop: "createDept",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "创建时间",
      prop: "createTime",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "修改人",
      prop: "updateUser",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "修改时间",
      prop: "updateTime",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "状态 up=1, down=0 ",
      prop: "status",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "是否已删除",
      prop: "isDeleted",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
  ]
}
