export default {
  size: 'small',
  expand: false,
  index: true,
  border: true,
  selection: true,
  column: [
    {
      label: "ID",
      prop: "id",
      display: false,
      hide: true,
    },
    {
      label: "ID",
      prop: "tenantId",
      search: true,
    },
    {
      label: "分销商名称",
      prop: "name",
    },
    {
      label: "等级",
      prop: "member",
      search: true,
    },
    {
      label: "电话",
      prop: "phone",
    },
    {
      label: "累计金额",
      prop: "totalconsumption",
    },
    {
      label: "消费金额",
      prop: "currentconsumption",
    },
    {
      label: "业绩",
      prop: "achievement",
    },
    {
      label: "二级分销订单总金额",
      prop: "childOrderMoney2",
      display: false,
      hide: true,
    },
    {
      label: "团队分销订单总金额",
      prop: "childOrderMoney",
      display: false,
      hide: true,
    },
    {
      label: "上级分销商",
      prop: "topdistributor",
    },
    {
      label: "一级用户",
      prop: "oneuser",
    },
    {
      label: "一级分销商",
      prop: "onedistributor",
    },
    {
      label: "一级用户",
      prop: "oneuser",
      display: false,
      hide: true,
    },
    {
      label: "直推分销商人数",
      prop: "childAgentCount1",
      display: false,
      hide: true,
    },
    {
      label: "二级分销商人数",
      prop: "childAgentCount2",
      display: false,
      hide: true,
    },
    {
      label: "团队分销商人数",
      prop: "childAgentCount",
      display: false,
      hide: true,
    },
    {
      label: "创建时间",
      prop: "time",
      format: "yyyy-MM-dd hh:mm:ss",
      valueFormat: "yyyy-MM-dd hh:mm:ss",
    },
    {
      label: "团队分销商等级统计",
      prop: "childAgentLevel",
      display: false,
      hide: true,
    },
    {
      label: "升级锁定:0=不锁定,1=锁定",
      prop: "upgradeLock",
      display: false,
      hide: true,
    },
    {
      label: "提交申请次数",
      prop: "applyNum",
      display: false,
      hide: true,
    },
    {
      label: "状态",
      prop: "state",
      search: true,
    },
    {
      label: "升级状态:0=不升级,1=待升级",
      prop: "levelStatus",
      display: false,
      hide: true,
    },
    {
      label: "成为分销商时间",
      prop: "becometime",
      display: false,
      hide: true,
    },
    {
      label: "操作",
      prop: "operation",
    },
    {
      label: "创建部门",
      prop: "createDept",
      display: false,
      hide: true,
    },
    {
      label: "创建时间",
      prop: "createTime",
      format: "yyyy-MM-dd hh:mm:ss",
      valueFormat: "yyyy-MM-dd hh:mm:ss",
      display: false,
      hide: true,
      search: true,
    },
    {
      label: "修改人",
      prop: "updateUser",
      display: false,
      hide: true,
    },
    {
      label: "结束时间",
      prop: "updateTime",
      format: "yyyy-MM-dd hh:mm:ss",
      valueFormat: "yyyy-MM-dd hh:mm:ss",
      display: false,
      hide: true,
      search: true,
    },
    {
      label: "分销商状态:-1:forbidden=禁用,0:pending=审核中,1:normal=正常",
      prop: "status",
      display: false,
      hide: true,
    },
    {
      label: "是否已删除",
      prop: "isDeleted",
      display: false,
      hide: true,
    },
  ]
}
